# Generated by Django 4.2.10 on 2024-02-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlA4cmZmx6Yz2kQR4vFabLzs7g3Ih4SWFy5lOeGxmlxg&s', max_length=1000),
        ),
    ]
